#数据库连接
mysql:
  host: localhost         #MySQL数据库服务器的地址
  port: 3306               #这里填写端口号
  db: blog                   #数据库名称
  user: root               #用户名
  password: 123456         #密码
  log_level: dev          #日志级别,意思是开发模式,可以设置为dev,prod,debug，打印日志
logger:
  level: info           #日志级别,意思是开发模式,可以设置为dev,prod,debug，打印日志
  prefix: '[gvb]'       #日志前缀
  director: log         #日志文件存放目录
  show-line: true       #是否显示行号
  log-in-console: true  #是否在控制台打印日志
system:
  host: "0.0.0.0"
  port: 8080          #监听的端口号
  env: dev      #运行环境,可以设置为dev,prod,debug，打印日志